### ISSUE TITLE
Notify user on FILE NOT FOUND

### ISSUE THREAD

**Issue by GitBruno** [fabianmoronzirfas/extendscript-bundlr#6]
It would be good to add a warning `FILE NOT FOUND` when running the script. It does put this line in the code:

    #include 'path/to/script.js'// FILE NOT FOUND by extendscript-bundlr

**Comment by fabianmoronzirfas** [comment]
sounds good.

**Comment by fabianmoronzirfas** [comment]
> A new version of the package extendscript-bundlr (0.4.0) was published at 2018-08-02T09:18:02.287Z
You can now add the flag `--missing` to see if there is a missing file

**Comment by GitBruno** [comment]
Loving the new `--missing` flag, comes out nicely coloured too. Great job man!
